name: Test

on: push

defaults:
  run:
    shell: bash

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: build
        run: |
          pnpm install
          pnpm vitest run
          pnpm -r build
